import { ACTION_TYPES, TARGETS, createAction, createCue, createProduction, createScene, createChamberDemo, normaliseProduction } from './model.js';
import { saveProduction, loadProduction, exportProduction, importProductionDocument } from './store.js';
import { runPreflight, hasBlockingIssues } from './preflight.js';
import { simulateCue, simulateScene } from './simulator.js';

const state={production:createChamberDemo(),activeSceneId:null,activeCueId:null,activeTab:'scenes'};
const $=selector=>document.querySelector(selector);
const els={productionName:$('#productionName'),productionMeta:$('#productionMeta'),sceneList:$('#sceneList'),sidebarEmpty:$('#sidebarEmpty'),sceneTitle:$('#sceneTitle'),sceneDescription:$('#sceneDescription'),cueList:$('#cueList'),cueCount:$('#cueCount'),cueTitle:$('#cueTitle'),cueTrigger:$('#cueTrigger'),actionStack:$('#actionStack'),composerEmpty:$('#composerEmpty'),preflightList:$('#preflightList'),issueCount:$('#issueCount'),readinessText:$('#readinessText'),readinessDetail:$('#readinessDetail'),simulatorLog:$('#simulatorLog'),saveState:$('#saveState'),modalRoot:$('#modalRoot'),toast:$('#toast'),fileInput:$('#productionFileInput')};
function activeScene(){return state.production.scenes.find(scene=>scene.id===state.activeSceneId)||null}function activeCue(){return activeScene()?.cues.find(cue=>cue.id===state.activeCueId)||null}function escapeHtml(value=''){const div=document.createElement('div');div.textContent=String(value);return div.innerHTML}function markDirty(){els.saveState.textContent='Unsaved changes'}
function toast(message){els.toast.textContent=message;els.toast.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>els.toast.classList.remove('show'),2300)}
function chooseDefaults(){if(!state.production.scenes.some(s=>s.id===state.activeSceneId))state.activeSceneId=state.production.scenes[0]?.id||null;const scene=activeScene();if(!scene?.cues.some(c=>c.id===state.activeCueId))state.activeCueId=scene?.cues[0]?.id||null}
function render(){chooseDefaults();els.productionName.value=state.production.name||'Untitled Production';const cueTotal=state.production.scenes.reduce((sum,scene)=>sum+scene.cues.length,0);els.productionMeta.textContent=`${state.production.scenes.length} scene${state.production.scenes.length===1?'':'s'} · ${cueTotal} cue${cueTotal===1?'':'s'} · v${state.production.version}`;renderScenes();renderSceneWorkspace();renderPreflight()}
function renderScenes(){els.sceneList.innerHTML='';els.sceneList.hidden=state.activeTab!=='scenes';els.sidebarEmpty.hidden=state.activeTab==='scenes';state.production.scenes.forEach((scene,index)=>{const button=document.createElement('button');button.className=`scene-card ${scene.id===state.activeSceneId?'active':''}`;button.innerHTML=`<span class="scene-number">SCENE ${String(index+1).padStart(2,'0')}</span><strong>${escapeHtml(scene.name)}</strong><span>${scene.cues.length} cue${scene.cues.length===1?'':'s'}</span>`;button.onclick=()=>{state.activeSceneId=scene.id;state.activeCueId=scene.cues[0]?.id||null;render()};els.sceneList.appendChild(button)})}
function renderSceneWorkspace(){const scene=activeScene(),cue=activeCue();els.sceneTitle.textContent=scene?.name||'No scene selected';els.sceneDescription.textContent=scene?.description||'Create a scene to begin composing the production.';els.cueList.innerHTML='';els.cueCount.textContent=scene?.cues.length||0;scene?.cues.forEach((item,index)=>{const button=document.createElement('button');button.className=`cue-card ${item.id===state.activeCueId?'active':''}`;button.innerHTML=`<span class="cue-index">${String(index+1).padStart(2,'0')}</span><span><strong>${escapeHtml(item.name)}</strong><span>${escapeHtml(item.trigger)}</span></span><span class="cue-actions-count">${item.actions.length} action${item.actions.length===1?'':'s'}</span>`;button.onclick=()=>{state.activeCueId=item.id;renderSceneWorkspace()};els.cueList.appendChild(button)});els.cueTitle.textContent=cue?.name||'Select a cue';els.cueTrigger.textContent=cue?`Trigger: ${cue.trigger}`:'Trigger: —';els.actionStack.innerHTML='';els.composerEmpty.hidden=Boolean(cue);if(!cue)return;cue.actions.forEach((action,index)=>{const def=ACTION_TYPES.find(item=>item.type===action.type)||ACTION_TYPES[0],card=document.createElement('article');card.className='action-card';card.innerHTML=`<div class="action-icon">${escapeHtml(def.icon)}</div><div><strong>${String(index+1).padStart(2,'0')} · ${escapeHtml(action.label)}</strong><p>${escapeHtml(action.value||def.label)}${action.delayMs?` · delay ${action.delayMs} ms`:''}${action.durationMs?` · ${action.durationMs} ms`:''}</p></div><button class="action-target" title="Edit action">${escapeHtml(action.target)}</button>`;card.querySelector('button').onclick=()=>openActionModal(action);els.actionStack.appendChild(card)})}
function renderPreflight(){const issues=runPreflight(state.production),errors=issues.filter(i=>i.level==='error').length,warnings=issues.filter(i=>i.level==='warn').length;els.preflightList.innerHTML=issues.map(i=>`<div class="preflight-item ${i.level}">${escapeHtml(i.text)}</div>`).join('');els.issueCount.textContent=errors+warnings;if(errors){els.readinessText.textContent='BLOCKED';els.readinessDetail.textContent=`${errors} blocking issue${errors===1?'':'s'} found.`}else if(warnings){els.readinessText.textContent='CHECK';els.readinessDetail.textContent=`${warnings} warning${warnings===1?'':'s'} before production export.`}else{els.readinessText.textContent='READY';els.readinessDetail.textContent='Production structure passes Studio 2.0 preflight.'}}
function openModal(title,fields,onSave){const backdrop=document.createElement('div');backdrop.className='modal-backdrop';const fieldHtml=fields.map(field=>field.type==='select'?`<label>${escapeHtml(field.label)}<select name="${field.name}">${field.options.map(option=>`<option value="${escapeHtml(option)}" ${option===field.value?'selected':''}>${escapeHtml(option)}</option>`).join('')}</select></label>`:field.type==='textarea'?`<label>${escapeHtml(field.label)}<textarea name="${field.name}">${escapeHtml(field.value||'')}</textarea></label>`:`<label>${escapeHtml(field.label)}<input name="${field.name}" type="${field.type||'text'}" value="${escapeHtml(field.value??'')}" /></label>`).join('');backdrop.innerHTML=`<form class="modal"><header>${escapeHtml(title)}</header><main>${fieldHtml}</main><footer><button type="button" data-cancel>Cancel</button><button class="primary" type="submit">Save</button></footer></form>`;const close=()=>backdrop.remove();backdrop.querySelector('[data-cancel]').onclick=close;backdrop.onclick=e=>{if(e.target===backdrop)close()};backdrop.querySelector('form').onsubmit=e=>{e.preventDefault();onSave(Object.fromEntries(new FormData(e.currentTarget).entries()));close();markDirty();render()};els.modalRoot.replaceChildren(backdrop)}
function addScene(){openModal('Add Scene',[{name:'name',label:'Scene name',value:`Scene ${state.production.scenes.length+1}`},{name:'description',label:'Purpose / description',type:'textarea',value:''}],v=>{const scene=createScene(v.name||'New Scene');scene.description=v.description||'';scene.order=state.production.scenes.length;state.production.scenes.push(scene);state.activeSceneId=scene.id;state.activeCueId=null})}
function renameScene(){const scene=activeScene();if(!scene)return toast('Select a scene first');openModal('Edit Scene',[{name:'name',label:'Scene name',value:scene.name},{name:'description',label:'Purpose / description',type:'textarea',value:scene.description}],v=>{scene.name=v.name||scene.name;scene.description=v.description||''})}
function addCue(){const scene=activeScene();if(!scene)return toast('Create a scene first');openModal('Add Cue',[{name:'name',label:'Cue name',value:`Cue ${scene.cues.length+1}`},{name:'trigger',label:'Trigger',value:'Operator GO'},{name:'notes',label:'Notes',type:'textarea',value:''}],v=>{const cue=createCue(v.name||'New Cue');cue.trigger=v.trigger||'Operator GO';cue.notes=v.notes||'';scene.cues.push(cue);state.activeCueId=cue.id})}
function editCue(){const cue=activeCue();if(!cue)return toast('Select a cue first');openModal('Edit Cue',[{name:'name',label:'Cue name',value:cue.name},{name:'trigger',label:'Trigger',value:cue.trigger},{name:'notes',label:'Notes',type:'textarea',value:cue.notes}],v=>{cue.name=v.name||cue.name;cue.trigger=v.trigger||'Operator GO';cue.notes=v.notes||''})}
function addAction(){const cue=activeCue();if(!cue)return toast('Select or create a cue first');openModal('Add Showduino Action',[{name:'type',label:'Action type',type:'select',value:'audio',options:ACTION_TYPES.map(i=>i.type)},{name:'label',label:'Action name',value:''},{name:'target',label:'Target',type:'select',value:TARGETS[0],options:TARGETS},{name:'value',label:'Command / asset / value',value:''},{name:'delayMs',label:'Delay before action (ms)',type:'number',value:0},{name:'durationMs',label:'Duration / fade (ms)',type:'number',value:0}],v=>{const action=createAction(v.type);action.label=v.label||ACTION_TYPES.find(i=>i.type===v.type)?.label||v.type;action.target=v.target;action.value=v.value||'';action.delayMs=Number(v.delayMs||0);action.durationMs=Number(v.durationMs||0);cue.actions.push(action)})}
function openActionModal(action){openModal('Edit Action',[{name:'type',label:'Action type',type:'select',value:action.type,options:ACTION_TYPES.map(i=>i.type)},{name:'label',label:'Action name',value:action.label},{name:'target',label:'Target',type:'select',value:action.target,options:TARGETS},{name:'value',label:'Command / asset / value',value:action.value},{name:'delayMs',label:'Delay before action (ms)',type:'number',value:action.delayMs},{name:'durationMs',label:'Duration / fade (ms)',type:'number',value:action.durationMs}],v=>{action.type=v.type;action.label=v.label||action.label;action.target=v.target;action.value=v.value||'';action.delayMs=Number(v.delayMs||0);action.durationMs=Number(v.durationMs||0)})}
function simulate(){const cue=activeCue(),scene=activeScene(),events=cue?simulateCue(cue):simulateScene(scene);els.simulatorLog.innerHTML='';if(!events.length){els.simulatorLog.innerHTML='<p>Nothing to simulate yet.</p>';return}events.forEach(event=>{const div=document.createElement('div');div.className='sim-event';div.innerHTML=event.kind==='cue'?`<strong>CUE ${event.cueIndex} · ${escapeHtml(event.cueName)}</strong><br>${escapeHtml(event.trigger)}`:`<strong>+${event.atMs||0} ms · ${escapeHtml(event.label)}</strong><br>${escapeHtml(event.type)} → ${escapeHtml(event.target)}${event.value?` · ${escapeHtml(event.value)}`:''}`;els.simulatorLog.appendChild(div)});toast(cue?`Simulated ${cue.name}`:`Simulated ${scene?.name||'scene'}`)}
function importProductionFile(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(String(reader.result));state.production=importProductionDocument(parsed);state.activeSceneId=null;state.activeCueId=null;state.production=saveProduction(state.production);render();els.saveState.textContent='Imported & saved';toast(`Imported ${state.production.name}`);window.dispatchEvent(new CustomEvent('showduino:production-imported'))}catch(error){console.error('Showduino import failed:',error);toast(error?.message||'That file is not a valid Showduino production')}};reader.readAsText(file)}
function exportForShowduino(){state.production.name=els.productionName.value.trim()||'Untitled Production';renderPreflight();if(hasBlockingIssues(state.production)){toast('EXPORT BLOCKED — fix Preflight errors first');return}state.production=saveProduction(state.production);exportProduction(state.production);els.saveState.textContent='Saved & exported for Showduino';toast('SHOWDUINO PACKAGE EXPORTED')}
$('#addSceneBtn').onclick=addScene;$('#renameSceneBtn').onclick=renameScene;$('#addCueBtn').onclick=addCue;$('#editCueBtn').onclick=editCue;$('#addActionBtn').onclick=addAction;$('#simulateBtn').onclick=simulate;$('#preflightBtn').onclick=()=>{renderPreflight();toast(hasBlockingIssues(state.production)?'Preflight found blocking errors':'Preflight complete')};$('#saveBtn').onclick=()=>{state.production.name=els.productionName.value.trim()||'Untitled Production';state.production=saveProduction(state.production);els.saveState.textContent=`Saved ${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`;render();toast('Production saved')};$('#loadBtn').onclick=()=>{const loaded=loadProduction();if(!loaded)return toast('No saved Studio 2.0 production found');state.production=normaliseProduction(loaded);state.activeSceneId=null;state.activeCueId=null;render();toast('Production loaded')};$('#newProductionBtn').onclick=()=>{state.production=createProduction('Untitled Production');state.activeSceneId=null;state.activeCueId=null;markDirty();render()};$('#exportBtn').onclick=exportForShowduino;$('#importBtn').onclick=()=>{els.fileInput.value='';els.fileInput.click()};els.fileInput.onchange=e=>importProductionFile(e.target.files?.[0]);els.productionName.oninput=()=>{state.production.name=els.productionName.value;markDirty();els.productionMeta.textContent=`${state.production.scenes.length} scenes · ${state.production.scenes.reduce((n,s)=>n+s.cues.length,0)} cues · v${state.production.version}`};
document.querySelectorAll('.section-tabs button').forEach(button=>button.onclick=()=>{state.activeTab=button.dataset.tab;document.querySelectorAll('.section-tabs button').forEach(item=>item.classList.toggle('active',item===button));renderScenes()});
state.activeSceneId=state.production.scenes[1]?.id||state.production.scenes[0]?.id||null;state.activeCueId=activeScene()?.cues[0]?.id||null;render();console.info('Showduino Studio 2.0 Production Foundation ready');
