import { ACTION_TYPES } from './model.js';

const TRACK_ORDER=['audio','lighting','pixel','dmx','relay','video','automation','trigger','safety','delay'];
const TRACK_LABELS={audio:'AUDIO',lighting:'LIGHTING',pixel:'PIXELS',dmx:'DMX',relay:'RELAYS',video:'VIDEO',automation:'AUTOMATION',trigger:'TRIGGERS',safety:'SAFETY',delay:'DELAYS'};
const MIN_CLIP_MS=500;
const SNAP_OPTIONS=[0,50,100,250,500,1000];
const ZOOM_MIN=30,ZOOM_MAX=180,ZOOM_STEP=10;
const engine={pxPerSecond:70,snapMs:250,currentMs:0,playing:false,raf:0,lastFrame:0,host:null,maxMs:30000,onTime:null};

function esc(value=''){const div=document.createElement('div');div.textContent=String(value);return div.innerHTML}
function actionStart(action,index){return Math.max(0,Number(action.timelineStartMs ?? action.delayMs ?? index*1000)||0)}
function actionDuration(action){return Math.max(MIN_CLIP_MS,Number(action.timelineDurationMs ?? action.durationMs ?? 2000)||2000)}
function seconds(ms){return ms/1000}
function snap(ms){return engine.snapMs?Math.round(ms/engine.snapMs)*engine.snapMs:Math.round(ms)}
function timecode(ms){ms=Math.max(0,Math.round(ms));const m=Math.floor(ms/60000),s=Math.floor(ms/1000)%60,x=ms%1000;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(x).padStart(3,'0')}`}
function stopClock(){engine.playing=false;cancelAnimationFrame(engine.raf);engine.raf=0;engine.lastFrame=0;engine.host?.querySelector('[data-play]')?.classList.remove('active')}
function updatePlayhead(autoScroll=false){if(!engine.host)return;const line=engine.host.querySelector('.timeline-playhead'),tc=engine.host.querySelector('[data-timecode]');if(line)line.style.left=`${86+seconds(engine.currentMs)*engine.pxPerSecond}px`;if(tc)tc.textContent=timecode(engine.currentMs);engine.onTime?.(engine.currentMs);if(autoScroll){const scroll=engine.host.querySelector('.timeline-scroll');if(scroll){const x=seconds(engine.currentMs)*engine.pxPerSecond;const visibleLeft=scroll.scrollLeft,visibleRight=visibleLeft+scroll.clientWidth-120;if(x>visibleRight)scroll.scrollLeft=Math.max(0,x-scroll.clientWidth*.35)}}}
function play(){if(engine.playing)return;engine.playing=true;engine.host?.querySelector('[data-play]')?.classList.add('active');engine.lastFrame=performance.now();const frame=now=>{if(!engine.playing)return;engine.currentMs+=now-engine.lastFrame;engine.lastFrame=now;if(engine.currentMs>=engine.maxMs){engine.currentMs=engine.maxMs;updatePlayhead(true);stopClock();return}updatePlayhead(true);engine.raf=requestAnimationFrame(frame)};engine.raf=requestAnimationFrame(frame)}
function pause(){stopClock()}
function rewind(){stopClock();engine.currentMs=0;updatePlayhead()}
function setTime(ms){engine.currentMs=Math.max(0,Math.min(engine.maxMs,snap(ms)));updatePlayhead()}

export function ensureTimeline(scene){if(!scene)return;let cursor=0;scene.cues.forEach(cue=>{cue.actions.forEach((action,index)=>{if(action.timelineStartMs==null)action.timelineStartMs=cursor+Number(action.delayMs||0)+index*650;if(action.timelineDurationMs==null)action.timelineDurationMs=Math.max(MIN_CLIP_MS,Number(action.durationMs||0)||2000)});const cueEnd=Math.max(0,...cue.actions.map((a,i)=>actionStart(a,i)+actionDuration(a)));cursor=Math.max(cursor+3000,cueEnd+700)})}

export function renderTimeline(host,scene,{onEdit,onChange,onTime}={}){
  if(!host)return;stopClock();engine.host=host;engine.onTime=onTime||null;
  if(!scene){host.innerHTML='<div class="timeline-empty">Create or select a scene to open the timeline.</div>';return}
  ensureTimeline(scene);
  const actions=scene.cues.flatMap(cue=>cue.actions.map(action=>({cue,action})));
  engine.maxMs=Math.max(30000,...actions.map(({action},i)=>actionStart(action,i)+actionDuration(action)+3000));engine.currentMs=Math.min(engine.currentMs,engine.maxMs);
  const width=Math.ceil(seconds(engine.maxMs)*engine.pxPerSecond);
  const used=new Set(actions.map(({action})=>action.type));
  const tracks=TRACK_ORDER.filter(type=>used.has(type)||['audio','lighting','pixel','relay'].includes(type));
  const tickMs=engine.pxPerSecond>=120?1000:engine.pxPerSecond>=60?5000:10000;
  const ticks=[];for(let ms=0;ms<=engine.maxMs;ms+=tickMs)ticks.push(`<span style="left:${seconds(ms)*engine.pxPerSecond}px">${timecode(ms).slice(0,5)}</span>`);
  host.innerHTML=`<div class="timeline-toolbar"><div class="timeline-title"><strong>MULTITRACK TIMELINE</strong><span>${esc(scene.name)}</span></div><div class="timeline-transport"><button data-rewind title="Return to zero">⏮</button><button data-play title="Play">▶</button><button data-pause title="Pause">⏸</button><button data-stop title="Stop">⏹</button><output data-timecode>${timecode(engine.currentMs)}</output></div><div class="timeline-tools"><label>SNAP <select data-snap>${SNAP_OPTIONS.map(v=>`<option value="${v}" ${v===engine.snapMs?'selected':''}>${v?`${v} ms`:'OFF'}</option>`).join('')}</select></label><button data-zoom-out title="Zoom out">−</button><span data-zoom>${engine.pxPerSecond}px/s</span><button data-zoom-in title="Zoom in">＋</button></div></div><div class="timeline-scroll"><div class="timeline-canvas" style="--timeline-width:${width}px"><div class="timeline-ruler"><div class="timeline-track-label">TIME</div><div class="timeline-ruler-grid" data-ruler style="width:${width}px">${ticks.join('')}</div></div>${tracks.map(type=>`<div class="timeline-track" data-track="${type}"><div class="timeline-track-label">${TRACK_LABELS[type]}</div><div class="timeline-lane" style="width:${width}px">${actions.filter(x=>x.action.type===type).map(({cue,action},i)=>{const def=ACTION_TYPES.find(d=>d.type===type)||{icon:'•'};const left=seconds(actionStart(action,i))*engine.pxPerSecond;const clipWidth=Math.max(48,seconds(actionDuration(action))*engine.pxPerSecond);return `<button class="timeline-clip clip-${type}" data-action="${esc(action.id)}" style="left:${left}px;width:${clipWidth}px" title="${esc(cue.name)} · ${esc(action.label)}"><b>${esc(def.icon)} ${esc(action.label)}</b><small>${esc(action.value||action.target)}</small><i class="timeline-resize" aria-hidden="true"></i></button>`}).join('')}</div></div>`).join('')}</div><div class="timeline-playhead" style="left:${86+seconds(engine.currentMs)*engine.pxPerSecond}px"><i></i></div></div>`;
  host.querySelector('[data-rewind]').onclick=rewind;host.querySelector('[data-play]').onclick=play;host.querySelector('[data-pause]').onclick=pause;host.querySelector('[data-stop]').onclick=rewind;
  host.querySelector('[data-snap]').onchange=e=>{engine.snapMs=Number(e.target.value);};
  const zoom=delta=>{const scroll=host.querySelector('.timeline-scroll');const centreMs=((scroll.scrollLeft+scroll.clientWidth/2)/engine.pxPerSecond)*1000;engine.pxPerSecond=Math.max(ZOOM_MIN,Math.min(ZOOM_MAX,engine.pxPerSecond+delta));renderTimeline(host,scene,{onEdit,onChange,onTime});const next=host.querySelector('.timeline-scroll');next.scrollLeft=Math.max(0,seconds(centreMs)*engine.pxPerSecond-next.clientWidth/2)};
  host.querySelector('[data-zoom-out]').onclick=()=>zoom(-ZOOM_STEP);host.querySelector('[data-zoom-in]').onclick=()=>zoom(ZOOM_STEP);
  const ruler=host.querySelector('[data-ruler]');ruler.addEventListener('pointerdown',e=>{stopClock();ruler.setPointerCapture(e.pointerId);const seek=ev=>{const rect=ruler.getBoundingClientRect();setTime((ev.clientX-rect.left)/engine.pxPerSecond*1000)};seek(e);const up=()=>{ruler.removeEventListener('pointermove',seek);ruler.removeEventListener('pointerup',up)};ruler.addEventListener('pointermove',seek);ruler.addEventListener('pointerup',up)});
  const findAction=id=>actions.find(x=>x.action.id===id)?.action;
  host.querySelectorAll('.timeline-clip').forEach(clip=>{const action=findAction(clip.dataset.action);if(!action)return;clip.addEventListener('click',()=>{if(!clip.dataset.moved&&onEdit)onEdit(action);clip.dataset.moved=''});clip.addEventListener('pointerdown',e=>{if(e.target.classList.contains('timeline-resize'))return;e.preventDefault();clip.setPointerCapture(e.pointerId);const startX=e.clientX,start=actionStart(action,0);clip.dataset.moved='';const move=ev=>{const delta=ev.clientX-startX;if(Math.abs(delta)>3)clip.dataset.moved='1';action.timelineStartMs=Math.max(0,snap(start+delta/engine.pxPerSecond*1000));clip.style.left=`${seconds(action.timelineStartMs)*engine.pxPerSecond}px`};const up=()=>{clip.removeEventListener('pointermove',move);clip.removeEventListener('pointerup',up);onChange?.(action)};clip.addEventListener('pointermove',move);clip.addEventListener('pointerup',up)});const handle=clip.querySelector('.timeline-resize');handle.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();handle.setPointerCapture(e.pointerId);const startX=e.clientX,start=actionDuration(action);const move=ev=>{action.timelineDurationMs=Math.max(MIN_CLIP_MS,snap(start+(ev.clientX-startX)/engine.pxPerSecond*1000));clip.style.width=`${Math.max(48,seconds(action.timelineDurationMs)*engine.pxPerSecond)}px`};const up=()=>{handle.removeEventListener('pointermove',move);handle.removeEventListener('pointerup',up);onChange?.(action)};handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',up)})});
  updatePlayhead();
}
